apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: osp-github-action-runner
spec:
  params:
    - name: REPO
      default: "openshift-pipelines/operator"
      description: "The GitHub repository in the format owner/repo (e.g., octocat/hello-world)"
    - name: GH_WORKFLOW_BRANCH
      default: "release-v1.21.x"
      description: "The source branch of the PR to trigger the initial workflow on"
    - name: WF_INPUTS
      default: |- 
          {"environment": "staging"}
    - name: GH_WORKFLOW_NAME
      default: operator-update-images
      description: "The name of the workflow file to trigger (e.g., test.yml)"
    - name: github-token-secret
      type: string
      default: "github-release"
      description: "Name of the secret containing the GitHub token"
    - name: github-token-key
      type: string
      default: "github-token"
      description: "Name of the secret containing the GitHub token"
  volumes:
    - name: github-secret-volume
      secret:
        secretName: $(params.github-token-secret)
    - name: shared-bin-dir
      emptyDir: { }
  stepTemplate:
    image: quay.io/openshift-pipeline/ci
    env:
      - name: BIN_DIR
        value: /shared-bin
      - name: PATH
        value: "/shared-bin:/usr/local/bin:/usr/bin"
      - name: GH_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.github-token-secret)
            key: $(params.github-token-key)
    volumeMounts:
      - name: shared-bin-dir
        mountPath: /shared-bin
      - name: github-secret-volume
        mountPath: /etc/github
        readOnly: true

  steps:
    - name: install-dependencies
      script: |
        echo $PATH
        
        echo "# 1. Create a local bin directory if it doesn't already exist"
        mkdir -p $BIN_DIR
        cd  /tmp
        
        echo "# 2. Fetch the latest version number from GitHub"
        VERSION=$(curl -s "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        
        
        GH_TAR_BALL=gh_${VERSION}_linux_amd64
        echo "Using gh cli $$GH_TAR_BALL"
        
        echo "# 3. Download the tarball"
        curl -sLO "https://github.com/cli/cli/releases/download/v${VERSION}/$GH_TAR_BALL.tar.gz"
        
        echo "# 4. Extract the tarball"
        tar -xf $GH_TAR_BALL.tar.gz
        
        # 5. Move the 'gh' binary to your local bin folder
        cp "gh_${VERSION}_linux_amd64/bin/gh" $BIN_DIR
        
        # 6. Clean up the downloaded files
        rm -rf $GH_TAR_BALL*
        
        ls -l $BIN_DIR
        echo $PATH
        
        gh --version
        gh auth status

    - name: trigger-and-wait-initial-workflow
      script: |
        #!/bin/sh
        export REPO="$(params.REPO)"
        export GH_WORKFLOW_BRANCH="$(params.GH_WORKFLOW_BRANCH)"
        
        echo $(params.WF_INPUTS) > /tmp/inputs.json
        
        cat << 'EOF' > /tmp/inputs.json
          $(params.WF_INPUTS)
        EOF

        echo "Triggering workflow $(params.GH_WORKFLOW_NAME) on branch $GH_WORKFLOW_BRANCH..."
        WF_RUN=$(
          gh workflow run "$(params.GH_WORKFLOW_NAME)" \
          -R $REPO \
          --ref "$GH_WORKFLOW_BRANCH" \
          --json < /tmp/inputs.json
        )

        echo "Sleeping for 10 seconds to allow GitHub to register the workflow run..."
        sleep 10
        
        RUN_ID="${WF_RUN##*/}"

        echo "Watching workflow run ID: $RUN_ID..."
        gh run watch $RUN_ID -R $REPO --exit-status

#    - name: merge-pull-request
#      script: |
#        #!/bin/sh
#        export REPO="-R $(params.REPO)"
#
#        echo "Merging PR #$(params.pr-number)..."
#        # You can change --merge to --squash or --rebase based on your repo requirements
#        gh pr merge "$(params.pr-number)" $REPO --merge --delete-branch=false
#        echo "Pull request merged successfully."
#
#    - name: wait-for-post-merge-build
#      script: |
#        #!/bin/sh
#        export REPO="-R $(params.REPO)"
#
#        echo "Sleeping for 15 seconds to allow the post-merge push event to trigger the next workflow..."
#        sleep 15
#
#        # Grabs the most recently triggered run on the target branch (e.g., main)
#        MERGE_RUN_ID=$(gh run list --branch "$(params.target-branch)" $REPO --json databaseId -q '.[0].databaseId')
#
#        if [ -z "$MERGE_RUN_ID" ] || [ "$MERGE_RUN_ID" == "null" ]; then
#          echo "Error: Could not find a running workflow for the push event on $(params.target-branch)."
#          exit 1
#        fi
#
#        echo "Watching post-merge workflow run ID: $MERGE_RUN_ID..."
#        gh run watch $MERGE_RUN_ID $REPO --exit-status
#        echo "Post-merge build finished successfully!"